version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: Asia/Jakarta
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
